spring:
   security:
      oauth2:
         client:
            registration:
               strava:
                  provider: strava-provider
                  client-id: ${strava.client.id}
                  client-secret: ${strava.client.secret}
                  client-authentication-method: POST
                  authorization-grant-type: authorization_code
                  redirect-uri: http://localhost:8080/login/oauth2/code/strava
                  scope: read
            provider:
               strava-provider:
                  tokenUri: https://www.strava.com/api/v3/oauth/token
                  authorizationUri: https://www.strava.com/api/v3/oauth/authorize?response_type=code
                  user-info-uri: https://www.strava.com/api/v3/athlete
                  user-name-attribute: id